apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: logging
data:
  elasticsearch.yml: |
    cluster.name: "docker-cluster"
    http.host: 0.0.0.0
    xpack.license.self_generated.type: trial
    xpack.security.enabled: false
    xpack.monitoring.collection.enabled: true
